schema-version = 1

[package]
title = "Basic UI React Native Application for project culturalaiworldtv"
version = "0.1.0"
id = "com.culturalai.worldtv"

[os.version]
min = "1.2"
target = "1.2"

[needs]
[[needs.module]]
id = "/com.amazon.vega.os@IVega_1_2"

[components]
[[components.interactive]]
id = "com.culturalai.worldtv.main"
runtime-module = "/com.amazon.kepler.runtime.react_native_kepler_4@IReactNativeKepler_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]

[wants]
# Web renderer service for rendering web content
[[wants.service]]
id = "com.amazon.webview.renderer_service"

# If Web App needs keyboard support
[[wants.service]]
id = "com.amazon.inputmethod.service"

# If Web App needs video playback
[[wants.service]]
id = "com.amazon.media.server"

# Required for emitting metrics from video playback
[[wants.service]]
id = "com.amazon.mediametrics.service"

# Required for video playback on stable APIs
[[wants.service]]
id = "com.amazon.mediabuffer.service"

[[wants.service]]
id = "com.amazon.mediatransform.service"

# If Web App needs audio playback
[[wants.service]]
id = "com.amazon.audio.stream"

# Required for audio management features to work in WebView
[[wants.service]]
id = "com.amazon.audio.control"

# To enable accessibility support for your app
[[wants.service]]
id = "com.amazon.kepler.ucc.publisher"

# Enable Group-IPC to access media services
[[wants.service]]
id = "com.amazon.gipc.uuid.*"

[offers]
[[offers.service]]
id = "com.amazon.gipc.uuid.*"
